project:
  type: website

website:
  title: "Julia Chahine"
  navbar:
    search: false
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: Julia_Chahine_CV.pdf
        text: CV
  page-navigation: false
      


format:
  html:
    theme: lux
    css: styles.css
    toc: true



