---
title: "About Me"
page-navigation: false
---

### Brown University

I am a second year Ph.D. student in Economics at Brown University. While at Brown, I am grateful to be supported by a National Science Foundation Graduate Research Fellowship. 

My broad research interests are in macroeconomic theory; in particular, expectations formation, monetary policy, and macro-finance (and occasionally a bit of growth). 

For the 2024-2025 year, I am the secretary of the economics Graduate Student Association. 

### University of Michigan

Prior to starting my Ph.D., I received a M.S. in Applied and Interdisciplinary Mathematics at the University of Michigan in Ann Arbor. 

At Michigan, I founded my passion for dynamic systems, complex analysis, and probability. Through courses and research in these areas, my then-tangential interest in economics grew; ultimately, compelling my application to economics Ph.D. programs.

### Colby College

I graduated from Colby College with a B.A. in Theoretical Mathematics and minors in both Economics and Philosophy. 

While at Colby, I was a member of their NCAA DI Alpine Ski Team. During my junior and senior years, I served at the captain of the team. 

### Beyond Academia

I like to be outside! Skiing will always have a special place in my heart, but I enjoy most activities that are accompanied by good views; hiking, biking, sailing, running, etc..

